### ISSUE TITLE
Do not use System.currentTimeMillis() to measure elapsed time

### ISSUE THREAD

**Issue by adutra** [vladimir-bukhtoyarov/rolling-metrics#18]
Hi, 

Thank you for this great library, I particularly appreciate your HdrHistogram-backed Reservoirs with reset capabilities.

However I noticed that you use `System.currentTimeMillis()` throughout the code to measure elapsed time, e.g. [here](https://github.com/vladimir-bukhtoyarov/rolling-metrics/blob/master/src/main/java/com/github/rollingmetrics/histogram/accumulator/ResetByChunksAccumulator.java#L80).

Shouldn't you be using `System.nanoTime()` instead? What happens if the machine's wall-clock time goes adrift, e.g. when changing daylight savings time?

**Comment by vladimir-bukhtoyarov** [comment]
> What happens if the machine's wall-clock time goes adrift, e.g. when changing daylight savings time?

Amount of problems depends from reset policy. Uniform and ResetOnSnapshot are not affected, ResetePeriodically and ResetPeriodicallyByChunks will produce inaccurate snapshots:
- If system time going forward then histogram will evict freshly recorded data, and client will miss measures.
- If system time going back then histogram will report obsolete data.

Thanks for attention for details, you are raised interesting problem. I will provide the fix in few days.

**Comment by vladimir-bukhtoyarov** [comment]
> I will provide the fix in few days.

**Comment by vladimir-bukhtoyarov** [comment]
Timezones with summer/winter time are not the problem, because ```System.currentTimeMillis()``` returns milliseconds in UTC, which by itself has no daylight savings time.

**To summarize the impact:**
The  ```System.currentTimeMillis()``` leads to inaccurate retention when machine time changed by administrator, or by unexpected reason.

**Comment by adutra** [comment]
Thank you for looking into this!
When you switch to nanoseconds, please be sure to account for numeric overflows, as explained in the javadocs of `System.nanoTime()`:

> To compare elapsed time against a timeout, use
       ```if (System.nanoTime() - startTime >= timeoutNanos) ...```
instead of
       ```if (System.nanoTime() >= startTime + timeoutNanos) ...```
because of the possibility of numerical overflow.

**Comment by vladimir-bukhtoyarov** [comment]
Done. will be released in scope of 3.0

**Comment by adutra** [comment]
Thank you!
