### ISSUE TITLE
`snapshot.getValues()` should return the values of the snapshot

### ISSUE THREAD

**Issue by rhart** [vladimir-bukhtoyarov/rolling-metrics#22]
I think `snapshot.getValues()` should return all the values of that snapshot and not all the percentile values.

Other reservoirs seem to behave this way and this example of a HDRH based reservoir does too https://bitbucket.org/marshallpierce/hdrhistogram-metrics-reservoir/src/51d0229044a0d470990fed1705913777bd63cbed/src/main/java/org/mpierce/metrics/reservoir/hdrhistogram/HistogramSnapshot.java?at=master&fileviewer=file-view-default#HistogramSnapshot.java-27

Similarly `snapshot.getSize()` should return `histogram.getTotalCount()`.

**Comment by vladimir-bukhtoyarov** [comment]
@rhart please [read this](https://github.com/vladimir-bukhtoyarov/rolling-metrics/blob/master/histograms.md#predefined-percentiles). By default the settings of histogram is optimized to avoid memory allocation and CPU utilization for data that not body interest.

You are able to achieve behaviour that you want by disabling snapshot optimization:
```java
builder.withoutSnapshotOptimization();
```

**Comment by rhart** [comment]
Ah, awesome. Many thanks
